import React, { useState } from 'react';

export default function SQLViewer({ sql }) {
  const [copied, setCopied] = useState(false);

  const copy = () => {
    navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={styles.card}>
      <div style={styles.header}>
        <span style={styles.label}>⚡ Generated SQL</span>
        <span style={styles.hint}>Generated by TinyLlama (local model)</span>
        <button style={styles.copyBtn} onClick={copy}>{copied ? '✅ Copied!' : '📋 Copy SQL'}</button>
      </div>
      <pre style={styles.code}>{sql}</pre>
    </div>
  );
}

const styles = {
  card: { background: '#1e1e2e', borderRadius: 12, padding: '18px 22px', marginBottom: 20 },
  header: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 },
  label: { color: '#a0d4a0', fontSize: 13, fontWeight: 700 },
  hint: { color: '#666', fontSize: 12, flex: 1 },
  copyBtn: { background: '#2d2d3e', color: '#ccc', border: '1px solid #444', borderRadius: 8, padding: '5px 14px', fontSize: 12, cursor: 'pointer' },
  code: { color: '#e2e8f0', fontSize: 13, lineHeight: 1.7, margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all', fontFamily: 'monospace' },
};
